### ISSUE TITLE
Add a duration to events

### ISSUE THREAD

**Issue by McPringle** [komunumo/komunumo-server#43]
e.g. 45 min or 1:30 h

**Comment by Shree-Gillorkar** [comment]
Hey @McPringle , I am new in open source contributing.  I would like work on this issue. Can you please tell me more details about it, like in which file do i have to look for the code related to it or in which file i have to make changes.

**Comment by McPringle** [comment]
Hi @Shree-Gillorkar, you are very welcome. First, you need to fork this repo and clone your fork to your local disk. Before starting coding on *Komunumo*, I recommend you try to start *Komunumo* on your development system. You need to setup a database, first. When you got it running, you can start making changes and look, if it still starts and changed the way you want.

Before I go into details: May you please try to check the README file if you can start *Komunumo*? If you run into problems, I might need to improve the documentation. :-)

**Comment by Shree-Gillorkar** [comment]
@McPringle okay, Thank you for your support. I will do the needful process and look into it. If any difficulty, will contact you soon.

**Comment by Shree-Gillorkar** [comment]
@McPringle , I was able to start the project in eclipse . The README file helped a lot. You can proceed with the other details of the project and let me know where in which file should i add the code for adding duration of the event.

**Comment by McPringle** [comment]
Sorry @Shree-Gillorkar, I missed your comment. I'm working on the dialog today and doing some refactoring. After it is done, I'm happy to tell you more about the steps to implement this new feature.

**Comment by McPringle** [comment]
My refactoring is done – fast than I thought. So you need to pull the new changes. To add a duration to events, you need to do several things:

- [ ] add a `duration` column of type `TIME` to the `event` table (after the `date` column because they belong together), `null` should be allowed (edit `V1_0_0__initialization.sql`)
- [ ] update generated `EventRecord` class by running `./mvnw compile`
- [ ] edit `EventDialog` class to add the new field to the form (method `createForm`)

If you need more information, especially editing the dialog, please feel free to ask.

**Comment by Shree-Gillorkar** [comment]
Hey @McPringle , I made the changes of the 1st step. I was facing some issues with 2nd & 3rd step. I guess my generated Evenrecord.java file is being crashed. I will soon try to resolve this.

**Comment by McPringle** [comment]
I merged your PR and checked the generation of the `EventRecord` class on my side. It looks good. You should run `./mvnw compile` again and check if you get a `BUILD SUCCESS` at the end. Which IDE do you use? The generated sources are written to the `target/generated-sources/jooq` directory. In some IDEs, you need to mark this directory as a source directory so the IDE knows, that it must look for source files there, too. In IntelliJ, for example, you just right-click the directory:

![image](https://user-images.githubusercontent.com/1254039/124358026-a9c01700-dc1e-11eb-9450-05d52cfd212a.png)

**Comment by Shree-Gillorkar** [comment]
@McPringle, Thanks for confirmation! I am having Eclipse and Visual Studio Code but currently i am using Eclipse IDE for this project. Thanks for guidance.  I will try to resolve this issue as soon as possible.

**Comment by Shree-Gillorkar** [comment]
Hey @McPringle , actually i never worked with ./mvnm complie file, MariaDB - Eclipse(together) and generated the class file. I just know the java and how to code with it. I tried to generate it but on 1st try it was generated & while opening it was crashed. I am trying it but still having some issues. Can you please guide me.

**Comment by McPringle** [comment]
`./mvnw compile` starts the compilation using Maven. Part of the compilation is the generation of database-related files. IDEs usually have this feature integrated. I'm not familiar with Eclipse, I'm using IntelliJ. There is a button in the Maven window:

![image](https://user-images.githubusercontent.com/1254039/124388872-0b4ab900-dce5-11eb-8788-fdef8b65a9b2.png)

I guess Eclipse should have something similar. But what works on every system, is the command line. What does Maven tell you, when you start it on the command line by running `./mvnw compile`? You should see something similar to this:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.14.12
```

Followed by many more lines and ending with a success message:

```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ komunumo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 64 source files to /Users/mcpringle/IdeaProjects/komunumo-server/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.762 s
[INFO] Finished at: 2021-07-04T15:51:54+02:00
[INFO] ------------------------------------------------------------------------
```

Did you get a similar output and `BUILD SUCCESS`? If not, what is the detailed error message?

**Comment by Shree-Gillorkar** [comment]
![image](https://user-images.githubusercontent.com/70030205/124390948-ab1b3d80-dd0b-11eb-8be5-8c4142b6c7f5.png)
It is giving this error. Can you please recognize it?

**Comment by McPringle** [comment]
The first error I can detect is this one:

![image](https://user-images.githubusercontent.com/1254039/124392529-6c2ebd00-dcf6-11eb-948f-ae696103eb26.png)

You have Maven 3.6.3 installed, which is a little bit old. Komunumo requires at Maven 3.8.1 or newer. I guess you have the following command:

```
mvn compile
```

This will use your locally installed version of Maven, which is version 3.6.3. You _can_ update your Maven installation, but you do not need to. Komunumo makes use of the Maven Wrapper. So you have to use this command (from your screenshot I guess you use Windows):

```
.\mvnw compile
```

This will use the Maven Wrapper bundled with the project and not touch your locally installed Maven. The Maven Wrapper in this project is configured to use Maven version 3.8.1.

Next: A screenshot is nice, but I can see only what is on the screen. One line of the error message, the most important one, is too long and does not fit on your screen, I can see only the first word of the error message ("Some"):

![image](https://user-images.githubusercontent.com/1254039/124392670-5cfc3f00-dcf7-11eb-8b85-28ca812fa6a8.png)

Better copy and paste the output from your console window as text into the GitHub comment. Here you can use the button with the angle bracket to format it as code (which will use a monospaced font and not break the lines):

![image](https://user-images.githubusercontent.com/1254039/124392753-9765dc00-dcf7-11eb-882e-9c54a48c74ec.png)

Step by step towards the finish line… :-)

**Comment by Shree-Gillorkar** [comment]
@McPringle thanks, I successfully solved the issue. 
![image](https://user-images.githubusercontent.com/70030205/124410688-9e790280-dd68-11eb-972b-2662e57ff2b9.png)

**Comment by Shree-Gillorkar** [comment]
Now the issue is where and how to compile ./mvnw compile to update generated EvenRecord.java file.

**Comment by McPringle** [comment]
Well, you did it already. The output on your screenshot comes from the compilation. Your version of the `EventRecord.java` should already contain the duration property.

**Comment by Shree-Gillorkar** [comment]
I am facing issue in EventDialog.java file 
Here is the code - 
/*
 * Komunumo - Open Source Community Manager
 * Copyright (C) Marcus Fihlon and the individual contributors to Komunumo.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.komunumo.ui.view.admin.events;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.validator.StringLengthValidator;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.komunumo.data.db.enums.EventLanguage;
import org.komunumo.data.db.enums.EventLevel;
import org.komunumo.data.db.enums.EventLocation;
import org.komunumo.data.db.tables.records.EventRecord;
import org.komunumo.data.db.tables.records.SpeakerRecord;
import org.komunumo.data.service.EventSpeakerService;
import org.komunumo.data.service.SpeakerService;
import org.komunumo.ui.component.KomunumoDateTimePicker;
import org.komunumo.ui.component.KomunumoEditDialog;
import org.vaadin.gatanaso.MultiselectComboBox;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Set;
import java.util.stream.Collectors;

public class EventDialog extends KomunumoEditDialog<EventRecord> {

    private final SpeakerService speakerService;
    private final EventSpeakerService eventSpeakerService;

    private Set<SpeakerRecord> speakers;
	

    public EventDialog(@NotNull final String title,
                       @NotNull final SpeakerService speakerService,
                       @NotNull final EventSpeakerService eventSpeakerService) {
        super(title);
        this.speakerService = speakerService;
        this.eventSpeakerService = eventSpeakerService;
    }

    @Override
    public void createForm() {
        final var title = new TextField("Title");
        final var subtitle = new TextField("Subtitle");
        final var speaker = new MultiselectComboBox<SpeakerRecord>("Speaker");
        final var abstrakt = new TextArea("Abstract");
        final var agenda = new TextArea("Agenda");
        final var level = new Select<>(EventLevel.values());
        final var language = new Select<>(EventLanguage.values());
        final var location = new Select<>(EventLocation.values());
        final var date = new KomunumoDateTimePicker("Date & Time");
        final var duration = new KomunumoDateTimePicker("Time");
        final var visible = new Checkbox("Visible");

        title.setRequiredIndicatorVisible(true);
        speaker.setOrdered(true);
        speaker.setItemLabelGenerator(value -> String.format("%s %s", value.getFirstName(), value.getLastName()));
        speaker.setItems(speakerService.getAllSpeakers());
        level.setLabel("Level");
        language.setLabel("Language");
        location.setLabel("Location");
        date.setMin(LocalDateTime.now());
        duration.setMin(LocalDateTime.now());
        visible.addValueChangeListener(changeEvent -> {
            final var value = changeEvent.getValue();
            speaker.setRequiredIndicatorVisible(value);
            level.setRequiredIndicatorVisible(value);
            abstrakt.setRequiredIndicatorVisible(value);
            language.setRequiredIndicatorVisible(value);
            location.setRequiredIndicatorVisible(value);
            date.setRequiredIndicatorVisible(value);
            duration.setRequiredIndicatorVisible(value);
            binder.validate();
        });

        formLayout.add(title, subtitle, speaker, level, abstrakt, agenda,
                language, location, date, duration, visible);

        binder.forField(title)
                .withValidator(new StringLengthValidator(
                        "Please enter the title of the event (max. 255 chars)", 1, 255))
                .bind(EventRecord::getTitle, EventRecord::setTitle);

        binder.forField(subtitle)
                .withValidator(new StringLengthValidator(
                        "The subtitle is too long (max. 255 chars)", 0, 255))
                .bind(EventRecord::getSubtitle, EventRecord::setSubtitle);

        binder.forField(speaker)
                .withValidator(value -> !visible.getValue() || value.size() >= 1,
                        "Please select at least one speaker")
                .bind(this::getSpeaker, this::setSpeaker);

        binder.forField(level)
                .withValidator(value -> !visible.getValue() || value != null,
                        "Please select a level")
                .bind(EventRecord::getLevel, EventRecord::setLevel);

        binder.forField(abstrakt)
                .withValidator(value -> !visible.getValue() || value != null && !value.isBlank(),
                        "Please enter the abstract")
                .bind(EventRecord::getAbstract, EventRecord::setAbstract);

        binder.forField(agenda)
                .bind(EventRecord::getAgenda, EventRecord::setAgenda);

        binder.forField(language)
                .withValidator(value -> !visible.getValue() || value != null,
                        "Please select a language")
                .bind(EventRecord::getLanguage, EventRecord::setLanguage);

        binder.forField(location)
                .withValidator(value -> !visible.getValue() || value != null,
                        "Please select a location")
                .bind(EventRecord::getLocation, EventRecord::setLocation);

        binder.forField(date)
                .withValidator(value -> !visible.getValue() && (value == null || value.isAfter(LocalDateTime.now()))
                                || value != null && value.isAfter(LocalDateTime.now()),
                        "Please enter a date and time in the future")
                .bind(EventRecord::getDate, EventRecord::setDate);

        binder.forField(duration)
               /* .withValidator(value -> !visible.getValue() && (value == null || value.isAfter(LocalTime.now()))
                		        || value !=null && value.isAfter(LocalTime.now()),
                        "Please enter duration")*/
                .bind(EventRecord::getDuration, EventRecord::setDuration);
        
        binder.forField(visible)
                .bind(EventRecord::getVisible, EventRecord::setVisible);
    }

    private Set<SpeakerRecord> getSpeaker(@NotNull final EventRecord record) {
        return speakers;
    }

    private void setSpeaker(@NotNull final EventRecord record, @Nullable final Set<SpeakerRecord> speakers) {
        this.speakers = speakers != null ? speakers : Set.of();
    }

    @Override
    public void open(@NotNull final EventRecord record, @Nullable final Callback afterSave) {
        speakers = eventSpeakerService.getSpeakersForEvent(record)
                .collect(Collectors.toSet());
        super.open(record, () -> {
            eventSpeakerService.setEventSpeakers(record, speakers);
            if (afterSave != null) {
                afterSave.execute();
            }
        });
    }
}


There is an error in  binder.forField(duration). Can you please help me solving this one.

**Comment by McPringle** [comment]
Checkout the first line of your error message, that is the most important one (the other two lines are related):

![image](https://user-images.githubusercontent.com/1254039/124729230-8cd25f00-df10-11eb-9972-7f30cc1713ad.png)

The duration is of type `LocalTime`, the return type of the descriptor is of type `LocalDateTime`. Do you see it? The first one is just the time, the second one is the date and the time. That does not match. If you take a look where you are creating the new field for the UI you will spot the problem:

```java
final var duration = new KomunumoDateTimePicker("Time");
```

You create a `KomunumoDateTimePicker`. Do you see the `Date` in there? But the duration has no date, just the time. In my comment a few days ago I told about the `TimePicker` component. There is no `Date` in the component name, so it uses no date and needs just time – exactly what you have in your duration. Check it out here: https://vaadin.com/components/vaadin-time-picker/

I guess you just copied the few lines of the event date field. So it is a classic copy-paste-error… ;-)

**Comment by Shree-Gillorkar** [comment]
Hey @McPringle , Sorry for delay. I was busy with my External Practical Exams. I will be free in 1-2 days. After that i will continue with the issue.
